// Re-export WS types from shared package — canonical source is @chatmosphere/shared
export type {
  WsMessageBase,
  JoinRoomMessage,
  LeaveRoomMessage,
  StatusChangeMessage,
  PingMessage,
  RequestBuddyPresenceMessage,
  AuthMessage,
  DmOpenMessage,
  DmCloseMessage,
  DmSendMessage,
  DmTypingMessage,
  DmTogglePersistMessage,
  RoomTypingMessage,
  SyncBlocksMessage,
  ClientMessage,
  NewMessageEvent,
  PresenceUpdateEvent,
  BuddyPresenceEvent,
  RoomJoinedEvent,
  PongEvent,
  ErrorEvent,
  RoomTypingEvent,
  DmOpenedEvent,
  DmMessageEvent,
  DmTypingEvent,
  DmPersistChangedEvent,
  DmIncomingEvent,
  ServerMessage,
} from '@chatmosphere/shared';
