# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'translator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10translator.proto\x12\x04nllb\"G\n\x10TranslateRequest\x12\x0f\n\x07sources\x18\x01 \x03(\t\x12\x10\n\x08src_lang\x18\x02 \x01(\t\x12\x10\n\x08tgt_lang\x18\x03 \x01(\t\")\n\x11TranslateResponse\x12\x14\n\x0ctranslations\x18\x01 \x03(\t2T\n\x12TranslationService\x12>\n\tTranslate\x12\x16.nllb.TranslateRequest\x1a\x17.nllb.TranslateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=26
  _globals['_TRANSLATEREQUEST']._serialized_end=97
  _globals['_TRANSLATERESPONSE']._serialized_start=99
  _globals['_TRANSLATERESPONSE']._serialized_end=140
  _globals['_TRANSLATIONSERVICE']._serialized_start=142
  _globals['_TRANSLATIONSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
